spring.application.name=demo

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cubetimer
spring.datasource.username=postgres
spring.datasource.password=13052006

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080
